name: icy_hot_hops_flamejam2023
description: A simple Flame game.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: 1.13.0
  flame_audio: 2.1.4
  flame_tiled: 1.18.2
  flutter:
    sdk: flutter
  leap: 0.5.3
  tiled: 0.10.1

dev_dependencies:
  flame_lint: 1.1.2
  flame_test: 1.15.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/dungeon_toolkit/
    - assets/images/pixel_platformer_tileset/background/
    - assets/images/pixel_platformer_tileset/cave/
    - assets/images/pixel_platformer_tileset/ice/
    - assets/images/pixel_platformer_tileset/grass/
    - assets/tiles/
